export const DASHBOARD_TAB = {
  FEEDBACK: "FEEDBACK",
  GRAPH: "GRAPH",
};
export const FEEDBACK_TAB_MODERATOR = [
  "PENDING FEEDBACK",
  "CHECKED FEEDBACK",
  "FLAGGED FEEDBACK",
  "FLAGGED COMMENT",
  "DISPUTED FEEDBACK"
  //"APPROVED",
  //"REJECTED",
  //"PENDING"

  // "FLAGGED FEEDBACK",
  // "BLOCKED LIST",
];
export const FEEDBACK_TAB_ADMIN = [
  "PENDING FEEDBACK",
  "CHECKED FEEDBACK",
  "FLAGGED FEEDBACK",
  "FLAGGED COMMENT",
  "DISPUTED FEEDBACK"
  // "BLOCKED LIST",
];

export const CAMPAIGNS_TAB = {
  ALL: "ALL",
  REFERRALS: "REFERRALS",
};
export const CAMPAIGNS_TAB_ALL = [
  "ONGOING CAMPAIGNS",
  "COMPLETED CAMPAIGNS",
  // "NEW USERS THROUGH CAMPAIGNS",
];
